/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("id.synth.rwls.application")
}

dependencies {
    implementation(libs.apache.commons.text)
    implementation(project(":utilities"))
}

application {
    // Define the main class for the application.
    mainClass.set("id.synth.rwls.app.AppKt")
}
